### ISSUE TITLE
No entiendo cómo configurar la máquina cuando me la bajo (OSX)

### ISSUE THREAD

**Issue by IndieLightAndMagic** [ivan-iver/vagrant_golang#2]
```
default: 22 (guest) => 2222 (host) (adapter 1)
```

==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...

**Comment by iver** [comment]
Este error se da generalmente por permisos en el host o bien alguna falla en el box que se generó. Lo voy a revisar. Por lo pronto puedes hacer ingresar con:

```
$ vagrant ssh
```

Si te pide usuario y contraseña, ambos son _vagrant_.

Avísame si tienes éxito o algún otro problema.

Saludos

**Comment by IndieLightAndMagic** [comment]
De acuerdo, pero la el box quedo bajado?
O debo de nuevo bajarlo?

**Comment by IndieLightAndMagic** [comment]
Gracias! Y puedo ver entonces los archivos locales en la máquina y en el host verdad?

**Comment by iver** [comment]
Hola.

Vagrant baja el box y lo instala. Si ya lo bajaste una vez, vagrant se encarga de gestionar si actualiza la máquina o no.

Si, puedes ver tus archivos dentro de vagrant en el directorio `/vagrant`.

Saludos.

**Comment by IndieLightAndMagic** [comment]
De acuerdo, pero en el host, qué directorio es? 
Vi en las configuraciones de la máquina virtual y no estoy seguro:

Mi directorio con Vagrant
`
iMac-de-Julian:vagrant_golang imac$ ls -la
total 64
drwxr-xr-x   9 imac  staff    306 Aug 31 11:57 .
drwxr-xr-x  43 imac  staff   1462 Aug 31 11:56 ..
drwxr-xr-x  13 imac  staff    442 Aug 31 11:56 .git
-rw-r--r--   1 imac  staff     10 Aug 31 11:56 .gitignore
drwxr-xr-x   3 imac  staff    102 Aug 31 11:57 .vagrant
-rw-r--r--   1 imac  staff  18047 Aug 31 11:56 LICENSE
-rw-r--r--   1 imac  staff   3408 Aug 31 11:56 README.md
-rw-r--r--   1 imac  staff   1048 Aug 31 11:56 Vagrantfile
drwxr-xr-x   4 imac  staff    136 Aug 31 11:56 bin
iMac-de-Julian:vagrant_golang imac$ 
`

Y en la máquina virtual:
`

vagrant $> ls -la
total 748
drwxr-xr-x 13 vagrant vagrant   4096 Sep  1 10:10 ./
drwxr-xr-x  3 root    root      4096 Feb  2  2015 ../
-rw-rw----  1 vagrant vagrant      5 Sep  1 10:43 A_
-rw-------  1 vagrant vagrant   1003 Apr  5 22:34 .bash_history
-rw-r--r--  1 vagrant vagrant    220 Feb  2  2015 .bash_logout
lrwxrwxrwx  1 vagrant vagrant     33 Apr  5 21:45 .bash_profile -> /home/vagrant/Config/bash_profile
-rw-r--r--  1 vagrant vagrant   1575 Feb  2  2015 .bashrc
drwx------  4 vagrant vagrant   4096 Aug 31 19:13 .cache/
drwxrwxr-x  6 vagrant vagrant   4096 Apr  5 21:22 Config/
-rw-rw----  1 vagrant vagrant     30 Aug 31 19:14 foo.txt
lrwxrwxrwx  1 vagrant vagrant     31 Apr  5 21:45 .gitconfig -> /home/vagrant/Config/git/config
lrwxrwxrwx  1 vagrant vagrant     41 Apr  5 21:45 .gitignore_global -> /home/vagrant/Config/git/gitignore_global
drwxrwxr-x  2 vagrant vagrant   4096 Apr  5 22:12 golang/
lrwxrwxrwx  1 vagrant vagrant     27 Apr  5 21:45 .nanorc -> /home/vagrant/Config/nanorc
-rw-r--r--  1 vagrant vagrant    675 Feb  2  2015 .profile
drwxrwxr-x  2 vagrant vagrant   4096 Apr  5 21:24 scripts/
-rw-r--r--  1 root    root    672917 Feb  2  2015 setuptools-12.0.5.zip
drwx------  2 vagrant vagrant   4096 Apr  5 21:45 .ssh/
lrwxrwxrwx  1 vagrant vagrant     30 Apr  5 21:45 .tmux.conf -> /home/vagrant/Config/tmux.conf
-rw-r--r--  1 vagrant vagrant      6 Feb  2  2015 .vbox_version
drwxrwxr-x  7 vagrant vagrant   4096 Apr  5 21:45 .vim/
drwxr-xr-x  2 vagrant vagrant   4096 Aug 31 19:14 .vimbackup/
-rw-------  1 vagrant vagrant    798 Aug 31 19:14 .viminfo
-rw-rw-r--  1 vagrant vagrant     36 Apr  5 21:45 .vimrc
drwxr-xr-x  2 vagrant vagrant   4096 Aug 31 19:14 .vimswap/
drwxr-xr-x  2 vagrant vagrant   4096 Apr  5 21:43 .vimundo/
drwxr-xr-x  2 vagrant vagrant   4096 Apr  5 21:43 .vimviews/
drwxrwxr-x  2 vagrant vagrant   4096 Feb  2  2015 .virtualenvs/

vagrant $> 
`

En la configuración de la máquina virtual en VBox tenemos:

vagrant : /Users/imac/vagrant_golang

Pero cree un archivo de texto A_ en la maquina y no la veo en mi host..... 
Qué estoy perdiendo de vista?

**Comment by IndieLightAndMagic** [comment]
Hola Ivan.

No pude sincronizar mi host con la máquina virtual

**Comment by iver** [comment]
Hola Julian.

En tu host tienes los archivos donde iniciaste vagrant, por ejemplo:

```
# Desde el host
$ pwd 
/Users/Iver/golang/
$ ls -l
total 56
-rw-rw----   1 Iver  staff    18K Apr  5 13:23 LICENSE
-rw-rw----   1 Iver  staff   3.3K Apr  5 13:23 README.md
-rw-r--r--   1 Iver  staff   1.0K Apr  5 18:01 Vagrantfile
```

ya dentro de la maquina virtual revisa lo siguiente:

```
$ vagrant up
$ vagrant ssh
$ pwd
/home/vagrant
# /home/vagrant -> no está sincronizado
$ cd /vagrant
$ pwd
/vagrant 
# si está sincronizado
$ ls -l
-rw-rw----  1 vagrant vagrant   18K Apr  5 13:23 LICENSE
-rw-rw----  1 vagrant vagrant   3.3K Apr  5 13:23 README.md
-rw-r----- 1 vagrant vagrant  1047 1.0K Apr  5 18:01 Vagrantfile
```

Espero con esto quede más claro. En caso de que no veas nada en `/vagrant/` entonces hay que revisar los logs del sistema. 

Comentame como te va :)

**Comment by IndieLightAndMagic** [comment]
Jeje ya pude.

Configure las llaves id_rsa:

`config.ssh.private_key_path = "~/.ssh/id_rsa"
`
Pegué la pública en el authorized de la VM

Y manualmente me tocó sincronizar el folder, es decir me toco especificarlo en vagrant:
`config.vm.synced_folder "./", "/home/vagrant"
  config.vm.synced_folder "../go_chat_server/", "/home/vagrant/Code/hack/go_chat_server/"
`
Y listo

ya ahí corrió bien
salieron unos errores
después go no funcionaba, así que lo reinstale
ahora voy a instalar upper.io

slds

Es realmente necesario la v1? para el curso de platzi?
No lo puedo hacer con la v2?

**Comment by iver** [comment]
Que bien Julian.

Seguro que con eso aprendiste bastante 👍 

En cuanto a go, la verdad es que es más fácil instalarlo sin la maquina virtual. Pero que bien que ya esta todo listo.

Y si, la versión 1 de upper te asegura que funciona como se dice en el curso. Pero el cambio con la v2 realmente no debería impactar mucho. 

Saludos.

**Comment by IndieLightAndMagic** [comment]
Bueno me voy a arriesgar, ya llevo +15 años arreglando problemas en UNix / Linux
Así que intentaré con upper.io v2 jeje.

**Comment by IndieLightAndMagic** [comment]
Oye una pregunta, en México si se está empleando gente que use go?
Es que a mi me encanto este lenguaje.... pero en Colombia no veo muchas ofertas de trabajo... todo es el mismo JAVA de siempre....

**Comment by iver** [comment]
Si, existen varias empresas que actualmente tienen `go` funcionando en producción. Existe una comunidad en México que sigue fomentando el uso del lenguaje y además ha generado más empleos debido a su implementación en empresas (startups y existentes) con proyectos nuevos.
